# Globalno (samo datum)
compatibility_date = "2024-09-23"

# ---------- API worker ----------
name = "api-worker"
main = "src/api.ts"
compatibility_flags = ["nodejs_compat"]

# (OPCIONO) Ako želiš i javnu rutu da ručno pozoveš iz browsera ili sa mašine:
# Dodaj ili promeni na svoj domen/zonu
# routes = [
#   { pattern = "api.tvoj-domen.com/run", zone_id = "<tvoja_zone_id>" }
# ]

# ---------- CRON worker kao dodatni "workerd" ----------
[[workerd]]
name = "cron-worker"
main = "src/cron.ts"
compatibility_flags = ["nodejs_compat"]

# CRON raspored – npr. svake 5 minuta
[workerd.triggers]
crons = ["* * * * *"]

# Service binding: CRON → API (interni poziv, ne treba javna ruta)
[[workerd.services]]
binding = "API"         # env.API u kodu
service = "api-worker"  # ime glavnog servisa iznad
