name = "cron-worker"
main = "cron.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["*/10 * * * *"]

[[services]]
binding = "API"
service = "api-worker"
